# Generated by Django 5.1.3 on 2025-04-14 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0006_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
