# Generated by Django 5.1.3 on 2025-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0009_alter_question_options_remove_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SC', 'Один вариант ответа'), ('MC', 'Несколько вариантов ответа'), ('TI', 'Ввод ответа вручную')], default='SC', max_length=2, verbose_name='Тип вопроса'),
        ),
    ]
