# Generated by Django 5.1.3 on 2025-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0010_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='selected_answers',
            field=models.ManyToManyField(blank=True, to='bmCourses.answer', verbose_name='Выбранные ответы'),
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='user_inputs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
