# Generated by Django 5.1.3 on 2025-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0011_usertestresult_selected_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='user_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
