# Generated by Django 5.1.3 on 2025-04-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0012_alter_usertestresult_user_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество попыток'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ограничение по времени в секундах'),
        ),
    ]
