# Generated by Django 5.1.3 on 2025-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmCourses', '0013_test_attempts_test_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_to_complete',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ограничение по времени в минутах'),
        ),
    ]
